#!/bin/sh

# This is device-hacks, a placeholder file for device-specific "hacks" or commands
# that has to be run on the GNU/Linux side at boot.


# To use, overlay a shell script to this file. By default, it'll run after
# lxc-android-config.service (the container), but one can override the behavior
# by overlaying device-hacks.service.d/device-specific-settings.conf or the
# device-hacks.service file itself.

# compat audio hal
mount -o bind /android/system/lib64/hw/audio.hidl_compat.default.so /android/vendor/lib64/hw/audio.primary.default.so
# fix mtp,adb
mount -o bind /dev/null /android/vendor/etc/init/init.samsungexynos7880.usb.rc
# force hwc2
#mount -o bind /dev/null /vendor/lib64/hw/hwcomposer.exynos5.so
